HTTP 400
{connection=[close], content-length=[47], content-type=[application/json], date=[Sat, 26 Sep 2026 13:56:44 GMT], x-request-id=[425a0fff-7af6-46b4-82e0-a2b58602a7eb]}

{"message":"Invalid order status","status":400}