HTTP 404
{content-length=[53], content-type=[application/json], date=[Sat, 26 Sep 2026 13:56:44 GMT], x-request-id=[5c449ada-db95-41ce-b1d5-4a9b4dc3ee40]}

{"message":"Order not found with ID: 1","status":404}